#
# https://hub.docker.com/r/thorwink/texlive
# thorwink:texlive:2020
# thorwink:texlive:latest
#

FROM thorwink/texlive:2020-minimal
LABEL maintainer="Thorsten Winkler <https://github.com/thorsten-winkler>"

ARG TL_PROFILE=texlive-2020-custom.profile
COPY $TL_PROFILE .

RUN apt update -y && apt upgrade -y && \
    tlmgr update --self && \
    cat $TL_PROFILE | grep collection | cut -d' ' -f1 | xargs tlmgr install
