#
# https://hub.docker.com/r/thorwink/texlive
# thorwink/texlive:2021-full
#

FROM thorwink/texlive:2021
LABEL maintainer="Thorsten Winkler <https://github.com/thorsten-winkler>"

RUN apt update -y && apt upgrade -y && \
    tlmgr update --self && \
    tlmgr install scheme-full
