#!/bin/bash

set -e

docker build -f Dockerfile.minimal -t thorwink/texlive:2019-minimal .
docker push thorwink/texlive:2019-minimal

docker build -f Dockerfile.custom -t thorwink/texlive:2019 .
docker push thorwink/texlive:2019
docker tag thorwink/texlive:2019 thorwink/texlive:latest
docker push thorwink/texlive:latest

docker build -f Dockerfile.full -t thorwink/texlive:2019-full .
docker push thorwink/texlive:2019-full
